### ISSUE TITLE
What should the format/encoding be when the data value is a "data:..." URL?

### ISSUE THREAD

**Issue by swcurran** [the-human-colossus-foundation/oca-spec#21]
For reference about this, please see [IETF RFC 2397](https://datatracker.ietf.org/doc/rfc2397/), and it's use is described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs). The \<tl;dr> is that a data URL consists of:

* Hardcoded string "data:"
* A media (MIME) type of the type of data
* An optional indicator that the data is base64 encoded (or not)
* the data

Example: `data:image/gif;base64,R0lGOD...AA7`

My question is what should be put into appropriate fields (format, encoding, standards) in the OCA Bundle for this kind of data?

I think the options are that we could have a set of values specific to a data URL so that the interpretation of the actual data value is determined at run time by evaluating the data element.

Alternatively, we could assume that the data will always be of a specific MIME type and duplicate the values to be in the data in the corresponding fields, likely with something like "IETF RFC 2397" in the "standards" overlay to indicate that a data URL is being used.

I think this will be a common way to encode data such as images in data structures (such as credentials). The Aries community is planning to use this, as it provides a way to detect an image in a credential when there is not an OCA Bundle available to provide more information about the data attribute.

What are your thoughts on that?

Is this something that should be defined in the OCA Specification?

**Comment by mitfik** [comment]
In OCA world the attribute can be any of supported [data type](https://oca.colossi.network/specification/#attribute-type) which means if you would like to have such string as a value for the attribute you would need use `Text` as this fits the most. 

If you would like to do it OCA-way instead of using `data-url` you should use attribute with type `Binary` and following overlays:

format:  image/gif
encoding: base64
standard: <if any>

You can see example in official documentation: https://oca.colossi.network/specification/#character-encoding-overlay

Then in the value you just keep the `data` since the rest is in overlays. This way you can separate data from semantic (in case of `data-url` everything is in value - which requires to parse the data and guess what to do with it base on what is inside, in OCA approach everything is explicit and clear ).

Hope that helps

If you would have follow up questions feel free to open that issue.
