### ISSUE TITLE
Editing the W3C document - tool? Respec.js?

### ISSUE THREAD

**Issue by neiljthomson** [the-human-colossus-foundation/oca-spec#3]
A problem with using raw HTML (vs. google docs, etc.) for defining a specification is commenting and flagging issues. 

This includes being able to comment in GitHub .md (MarkDown), as to what your contribution/comment applies to (e.g. can't highlight a word, section, etc. and "insert comment").

A quick search turns up the respect.js editing approach, which is described here:

Tutorial - Editing ReSpec documents for W3C Credentials Community Group (https://www.youtube.com/watch?v=0eQXU6Z-A6Q) with an intro by Manu Sporny. 

This is REQUIRED viewing if you have not worked with the W3C RFP spec format before.

The website (and user manual) for ReSpec.js: https://respec.org/docs/

Unclear what tools are being used for this RFC, or how best to identify where in the doc that a comment or input applies other than to specify the section number/para number/ and "starts with:" <this text>

Unless you are using guidelines, tools and techniques that are not yet on this GitHub site.

**Comment by bserdar** [comment]
@neiljthomson creating a pull request with the changes you are proposing will allow inserting such comments.

**Comment by neiljthomson** [comment]
@bserdar fair enough. Was looking more to what common technique we want to use. One or more of
 - Use Pull + ReSpec.js 
 - Put comments in GitHub Issue
  - ....

**Comment by neiljthomson** [comment]
The website (and user manual) for ReSpec.js:

https://respec.org/docs/

**Comment by KDean-Dolphin** [comment]
(Coming to this a year late.)

I agree. GitHub isn't conducive to the kind of editing required for human-readable documents. Pull requests don't work well, for a couple reasons:

- I may make more than one change to a document, and the changes I make may be completely unrelated. I would have to create a separate commit plus pull request for each so that they can be accepted or rejected individually.
- I may not want to make a change at all, but rather make a comment, which would trigger a discussion, which would then trigger a change. No change, though, means no commit and no pull request.

**Comment by mitfik** [comment]
For any suggestion and open topics please open an issue, for contribution or change suggestion please open PR with proposed changes. 

github ain't perfect but we need to work with what we have.
