### ISSUE TITLE
Adding multiple locals to a single overlay

### ISSUE THREAD

**Issue by carlyh-micb** [the-human-colossus-foundation/oca-spec#47]
Overlays may be required for a single language but cover multiple locals (though not all).

Could one overlay say:
language=["en"]

and then another overlay would be:

language=["en-CA","en-GB"]
which would contain the UK/Canada specific variations (colour instead of color)

be accepted for any language specific overlays?

**Comment by pknowl** [comment]
I suggest keeping language and locale as valid entries for any "language" attribute. In other words, The following entries would result in separate overlay instances.

_"en"_
_"en-CA"_
_"en-GB"_
_"en-US"_

This would ensure that all overlay instances involving either language or locale remain clean. Written language tends to change slightly per locale.

For example, there are several examples where British English ("en-GB") and Canadian English ("en-CA") spellings differ slightly, often due to Canadian English blending British and American influences. One such example is the word "colour" in British English, which is spelled "color" in American English. Canadian English typically aligns with the British spelling, using "colour." However, for certain words, Canadian English may lean towards American spellings or have its own unique conventions.

For instance, the word "organize" in Canadian English typically follows the American spelling with a "z," rather than the British "organise" with an "s." This reflects the general Canadian practice of using "-ize" endings, which is also favored by some British publications and dictionaries based on etymological reasons. Thus, while "colour" demonstrates a direct alignment with British spelling, "organize" showcases a slight deviation towards American preferences within Canadian English.

**Comment by carlyh-micb** [comment]
Does you recommendation mean you couldn't remove a duplication of the same overlay by having:

language=["en-CA","en-GB"]

If the overlays are the same, what is the benefit of recreating the same overlay and then having to update two and keep the two of them the same? If they become different in the future I could then choose to split.

**Comment by carlyh-micb** [comment]
What is an official OCA example of a language/country code?

"combined language (lowercase)/country (uppercase) code" from the OCA spec.

Is en-CA correct, or en/CA?

ChatGPT says: "The correct representation for Canadian English in language tags, as defined by the IETF BCP 47 standard, is "en-CA". This follows the pattern of using a hyphen to separate the language code (en for English) from the region code (CA for Canada)."

**Comment by pknowl** [comment]
"en-CA" is the correct format. http://www.lingoes.net/en/translator/langcode.htm
